/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package limpiadorexcel;

import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.JFrame;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import jxl.write.WriteException;
import static limpiadorexcel.GestorExcel.llenarArreglos;

/**
 *
 * @author eddyp
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    File rutarchivo;
    static boolean mostrarBotones = false;
    
    public VentanaPrincipal() {
        initComponents();
        this.getContentPane().setBackground(Color.WHITE);
        this.setSize(300, 500);
        //jButtonCofig1.setVisible(false);
        BotonGenerar.setVisible(false);
        PanelBotones.setVisible(false);
        BotonBorrar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelBotones = new javax.swing.JPanel();
        BotonBuscarLeer = new javax.swing.JButton();
        BotonGenerar = new javax.swing.JButton();
        BotonSalir = new javax.swing.JButton();
        BotonBorrar = new javax.swing.JButton();
        jButtonCofig1 = new javax.swing.JButton();
        jButtonConfigBoton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuAyuda = new javax.swing.JMenu();
        jMenuInstrucciones = new javax.swing.JMenuItem();
        jMenuCreditos = new javax.swing.JMenu();
        jMenuItemInformación = new javax.swing.JMenuItem();
        jMenuCerrar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ventana Principal");
        setBackground(javax.swing.UIManager.getDefaults().getColor("Button.disabledShadow"));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelBotones.setBackground(java.awt.SystemColor.inactiveCaption);
        PanelBotones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PanelBotones.setLayout(new java.awt.GridLayout(0, 4));
        getContentPane().add(PanelBotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 740, 460));

        BotonBuscarLeer.setBackground(new java.awt.Color(255, 255, 255));
        BotonBuscarLeer.setText("Buscar Archivo");
        BotonBuscarLeer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBuscarLeerActionPerformed(evt);
            }
        });
        getContentPane().add(BotonBuscarLeer, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 145, 100));

        BotonGenerar.setBackground(new java.awt.Color(255, 255, 255));
        BotonGenerar.setText("Limpiar Archivo");
        BotonGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGenerarActionPerformed(evt);
            }
        });
        getContentPane().add(BotonGenerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, 93));

        BotonSalir.setBackground(new java.awt.Color(255, 255, 255));
        BotonSalir.setText("SALIR");
        BotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(BotonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, -1, -1));

        BotonBorrar.setBackground(new java.awt.Color(255, 255, 255));
        BotonBorrar.setText("Elimiar Archivo");
        BotonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBorrarActionPerformed(evt);
            }
        });
        getContentPane().add(BotonBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, -1, -1));

        jButtonCofig1.setText("Contiguracion 1");
        jButtonCofig1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCofig1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCofig1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 50, -1, -1));

        jButtonConfigBoton.setText("CONFIGURAR");
        jButtonConfigBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfigBotonActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonConfigBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 410, 140, 80));

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));

        jMenuAyuda.setText("AYUDA");

        jMenuInstrucciones.setText("Instrucciones");
        jMenuInstrucciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuInstruccionesActionPerformed(evt);
            }
        });
        jMenuAyuda.add(jMenuInstrucciones);

        jMenuBar1.add(jMenuAyuda);

        jMenuCreditos.setText("CREDITOS");
        jMenuCreditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCreditosActionPerformed(evt);
            }
        });

        jMenuItemInformación.setText("Información");
        jMenuItemInformación.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemInformaciónActionPerformed(evt);
            }
        });
        jMenuCreditos.add(jMenuItemInformación);

        jMenuBar1.add(jMenuCreditos);

        jMenuCerrar.setText("SALIR");
        jMenuCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuCerrarMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuCerrar);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonBuscarLeerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBuscarLeerActionPerformed
    rutarchivo=GestorExcel.obtenerArchivo();
    PanelBotones.setVisible(true);
    BotonBorrar.setVisible(true);
        try {
            
            if (rutarchivo==null){
                BotonBorrar.setVisible(false);
                BotonGenerar.setVisible(false);
                PanelBotones.setVisible(false);
            }else{
                this.setSize(1200,600);
                BotonGenerar.setVisible(true);
                llenarArreglos(rutarchivo);
            }
        } catch (IOException ex) {
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        PanelBotones.updateUI();
    }//GEN-LAST:event_BotonBuscarLeerActionPerformed

    private void BotonGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGenerarActionPerformed
        String NombreBoton="";
        /*if (ElementosEstaticos.ListaBotones.isEmpty()){
            JOptionPane.showMessageDialog(null, "No se ha cargado archivo");
        }else{
            for (int i = 0;i<ElementosEstaticos.ListaBotones.size();i++){
                if (ElementosEstaticos.ListaBotones.get(i).isSelected()){
                    JOptionPane.showMessageDialog(null, ElementosEstaticos.ListaBotones.get(i).getText());
                }
            }
        }*/
        ElementosEstaticos.Matriz.clear();
        if (ElementosEstaticos.ListaBotones.isEmpty()){
            JOptionPane.showMessageDialog(null, "No se ha cargado archivo");
        }else{
            for (int i = 0;i<ElementosEstaticos.ListaBotones.size();i++){
                if (ElementosEstaticos.ListaBotones.get(i).isSelected()){
                    NombreBoton=ElementosEstaticos.ListaBotones.get(i).getText();
                    //JOptionPane.showMessageDialog(null, "Seleccionado: "+NombreBoton);
                    try {
                        GestorExcel.LlenarColumna(NombreBoton,rutarchivo);
                        //GestorExcel.LlenarColumnaExcel(new File("C:\\Users\\eddyp\\Desktop\\nuevo.xls"));
                        //JOptionPane.showMessageDialog(null, "Tamaño Matriz: "+String.valueOf(ElementosEstaticos.Matriz.size()));
                    } catch (IOException ex) {
                        Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }
/*-----------------------------------------------------------se crea el archivo final*/        
        try {
            GestorExcel.LlenarColumnaExcel(GestorExcel.obtenerRutaGuardado());
        } catch (IOException ex) {
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (WriteException ex) {
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        //GestorExcel.ImprimirArreglo();
    }//GEN-LAST:event_BotonGenerarActionPerformed

    private void BotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BotonSalirActionPerformed

    private void jMenuInstruccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuInstruccionesActionPerformed
        JOptionPane.showMessageDialog(null, "1. Presionar botón BUSCAR ARCHIVO\n"+
                                                  "2. Seleccionar archivo Excel (.xlms)\n"+
                                                  "3. Seleccionar los cuadros que desean ser guardados\n"+
                                                  "4. Presionar botón LIMPIAR ARCHIVO y seleccionar donde\n"+
                                                  "será guardado");
    }//GEN-LAST:event_jMenuInstruccionesActionPerformed

    private void BotonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBorrarActionPerformed
        ElementosEstaticos.Matriz.clear();
        ElementosEstaticos.ListaBotones.clear();
        ElementosEstaticos.BotonesSelecciones.clear();
        ElementosEstaticos.ListaCadenas.clear();
        PanelBotones.updateUI();
        rutarchivo=null;
        PanelBotones.setVisible(false);
        BotonGenerar.setVisible(false);
        BotonBorrar.setVisible(false);
    }//GEN-LAST:event_BotonBorrarActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        
    }//GEN-LAST:event_formWindowActivated

    private void jMenuCreditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCreditosActionPerformed
        
    }//GEN-LAST:event_jMenuCreditosActionPerformed

    private void jMenuItemInformaciónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemInformaciónActionPerformed
        JOptionPane.showMessageDialog(null, "Desarrollador: Eduardo Alberto Pereda Guzmán\n"
                                            +"Ultima Actualización: 29/08/2018\n\n"
                                            +"Ultimas Novedades:\nVersion 1.1\n"
                                            +"Corrección de Bugs en elección de archivos");
    }//GEN-LAST:event_jMenuItemInformaciónActionPerformed

    private void jButtonConfigBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfigBotonActionPerformed

        for (int i=0;i<ElementosEstaticos.ListaBotones.size();i++){
            if (ElementosEstaticos.ListaBotones.get(i).isSelected()){
                ElementosEstaticos.BotonesSelecciones.add(ElementosEstaticos.ListaBotones.get(i).getText());
            }
        }
        GestorExcel.generarArchivoTexto(new File("configuraciones\\Boton1.txt"));
        jButtonCofig1.setVisible(true);
    }//GEN-LAST:event_jButtonConfigBotonActionPerformed

    private void jButtonCofig1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCofig1ActionPerformed
        
        GestorExcel.PresionarBotonesConfiguracion(new File("configuraciones\\Boton1.txt"));
    }//GEN-LAST:event_jButtonCofig1ActionPerformed

    private void jMenuCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuCerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jMenuCerrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton BotonBorrar;
    private javax.swing.JButton BotonBuscarLeer;
    public static javax.swing.JButton BotonGenerar;
    private javax.swing.JButton BotonSalir;
    public static javax.swing.JPanel PanelBotones;
    private javax.swing.JButton jButtonCofig1;
    private javax.swing.JButton jButtonConfigBoton;
    private javax.swing.JMenu jMenuAyuda;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCerrar;
    private javax.swing.JMenu jMenuCreditos;
    private javax.swing.JMenuItem jMenuInstrucciones;
    private javax.swing.JMenuItem jMenuItemInformación;
    // End of variables declaration//GEN-END:variables
}
